# Site settings
title: Yiwei Zhang, SwiftUI + React Native + Node.js
description: "A blog about Yiwei Zhang."
baseurl: "/zywkloo.github.io" # for test: remove string '/space-jekyll-template' to ''
url: "https://zywkloo.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: Yiwei Zhang
user_title: React/Node.js/Swift Developer
email: yiweizhangca@gmail.com
twitter_username: zywkloo
github_username:  zywkloo
gplus_username: 116814196032329811422
linkedin_public_url: yiweiZ315
profile_picture: https://github.com/zywkloo/myLeetCodePractice/raw/master/pics/Avatar.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: Home
      url: /
      key_trigger: 1
    - title: Posts
      url: /series
      key_trigger: 2
    - title: Tags
      url: /tags
      key_trigger: 3
    - title: About Me
      url: /about
      key_trigger: 4
  section_2:
    - title: AI
      url: /BoardGameAIDevelopment/
      key_trigger: a
    - title: Gaming
      url: /space/
      key_trigger: p
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index

projects:
  - name: TutorOcean iOS App - Node.js & SwiftUI
    url: https://apps.apple.com/ca/app/tutorocean/id1480876532
  - name: cuHacking20 Winner - Plotly Data Visualiztion 
    url: https://devpost.com/software/murder-on-2nd-floor-web-forensic-analyzer
  - name: cuHacking19 Winner - AWS Connect Integration
    url: https://devpost.com/software/cuhackingamazonconnect
  - name: Xchangerator(Exchange Rate Query) - Express & SwiftUI
    url: https://github.com/zywkloo/Xchangerator
  - name: Mobile Game Wild Dunk (全民大灌篮)
    url: https://www.youtube.com/watch?time_continue=6&v=ysmp5vK4R_c
  - name: GameAI:Tank Tournament w/ Pygame
    url: https://github.com/zywkloo/Tank-Game-AI-Tournament
  - name: Insomnia-Dungeon. Mini game w/ Pygame
    url: https://github.com/zywkloo/Insomnia-Dungeon
   

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
